### ISSUE TITLE
Not showing up on Chrome 83 when Developer Tools is opened

### ISSUE THREAD

**Issue by matt-cheng** [MisterPhilip/omnibug#100]
**Describe the bug**
The Omnibug option intermittently displays when opening up the Devtools. Sometimes it'll be there, some times it won't.

**To Reproduce**
1. Go to https://abcnews.go.com/
2. Open Dev Tools
3. Observe missing Omnibug option

**Expected behavior**
The Omnibug option should show up with the other Devtool options (Network, Console, Elements, etc)

**Screenshots**
<img width="1590" alt="Screen Shot 2020-06-03 at 3 17 43 PM" src="https://user-images.githubusercontent.com/10816479/83694676-66bfea00-a5ad-11ea-9e1b-80a75d45a297.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Version: 83.0.4103.97
 - Omnibug Version 1.16.0

**Additional context**

**Comment by MisterPhilip** [comment]
Thanks - I noticed it this morning and have been debugging it. I suspect it is a Chrome bug, but will be taking a deeper look into it.

**Comment by MisterPhilip** [comment]
Bug logged with the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1091043

**Comment by matt-cheng** [comment]
Updated to Chrome Version 84.0.4147.89 and so far the Omnibug option shows up every time pull up the developer tools.

**Comment by MisterPhilip** [comment]
Excellent. I've seen a few instances of it not, but it's doing a lot better than it was in v83. I'll keep this open to ensure that it is consistently opening with devtools, but let me know if you are having troubles again!

**Comment by MisterPhilip** [comment]
Looks like things are _much_ better now. Closing it for now, but let me know if you see it pop back up. Thanks again for the report!
