### ISSUE TITLE
Highlight color doesn't match the color set for Video Analytics calls

### ISSUE THREAD

**Issue by matt-cheng** [MisterPhilip/omnibug#101]
**Describe the bug**
The highlighted parameter's color doesn't match with what I have in my settings. It's showing up as blue rather than yellow.
Page/Click calls highlight as expected.

**To Reproduce**
1. Go to Omnibug settings and add a video parameter to highlight
2. Go to abc.com
3. Start any video
4. Observe video analytics start call

**Expected behavior**
Highlight color should match what I have set. 

**Screenshots**
<img width="602" alt="Screen Shot 2020-06-03 at 4 55 44 PM" src="https://user-images.githubusercontent.com/10816479/83700439-b9a09e00-a5bb-11ea-8cc1-c4f8575c1e3d.png">

<img width="403" alt="Screen Shot 2020-06-03 at 4 56 08 PM" src="https://user-images.githubusercontent.com/10816479/83700447-bd342500-a5bb-11ea-8d9d-abc28020eacb.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome
 - Version 83
 - Omnibug Version 1.16.0

**Additional context**

**Comment by matt-cheng** [comment]
Would this have something to do with dark mode? Looks like regular click and page calls are also highlighting as blue.

**Comment by MisterPhilip** [comment]
Yeah, I have it set to overwrite for dark mode since the default yellow is pretty jarring on dark mode. Thinking of a fix for it; likely just use the setting instead of overwriting it - thoughts?

Also I'll say that you're one of the few people that have even noticed there is a setting for changing the colors, haha!

**Comment by matt-cheng** [comment]
How you have it now is probably what works best. I agree that yellow would be jarring with dark mode enabled. Perhaps it would be good to have an override option within the settings when dark mode in enabled. Like a "you're using dark mode. you sure you want to change this color to xyz?"
