### ISSUE TITLE
Make Highlight Parameters case insensitive

### ISSUE THREAD

**Issue by matt-cheng** [MisterPhilip/omnibug#102]
**Is your feature request related to a problem? Please describe.**
Not a problem, more like an enhancement so you don't need to enter multiple entries if the context variable is capitalized in one area vs. not in another.

**Describe the solution you'd like**
Context variables that are added to be highlighted should be case insensitive. ie if a variable is publishdate vs PublishDate, it should both highlight without having to specify for both cases.

**Describe alternatives you've considered**

**Additional context**

**Comment by MisterPhilip** [comment]
Sorry I missed this one - yeah, I'd agree on this. I'll add it in the next update!
