### ISSUE TITLE
Custom Rules - Import/Export feature

### ISSUE THREAD

**Issue by tjtate** [MisterPhilip/omnibug#104]
You have all the makings here to be able to add a section in the UI to allow people to add their own providers, which i believe would make this the most widely used plugin for pixel debugging. if you had a structured json format you could allow people to set the rules in the UI and then you could have an export feature that could download a json file and allow other users to upload it to their extensions to take advantage of the settings (think postman import/exports) I cant use this now because i have several ad networks that are not currently supported. outbrain, dianomi, adblade, hasoffers, etc. just a thought. i love this plugin!!! but unfortunately cant have my marketers use it as is.

**Comment by MisterPhilip** [comment]
Hi @tjtate - 

Yeah, this is definitely something I've been wanting to add into Omnibug for a while now. The biggest challenge is most providers have semi-complex logic for getting dynamic keys, cleaning up values, etc. For example, the Facebook provider [checks for custom dimensions](https://github.com/MisterPhilip/omnibug/blob/master/src/providers/FacebookPixel.js#L162) for any parameter that starts with `cd[`, then replaces the key name from `cd[test]` to `test`.  For providers that just need a straight mapping with no tweaks, then we could add in a way to add your own providers. 

Would allowing just basic parameters suffice for you, or do you think you'd need something more advanced than that?
