### ISSUE TITLE
Adobe launch web property and virtual report suite name

### ISSUE THREAD

**Issue by Jayap3** [MisterPhilip/omnibug#107]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It would be good if we get the respective launch web property name and virtual report suite name for the particular site. I hope this wasn't active currently.

**Comment by MisterPhilip** [comment]
Both would require an API connection to Adobe, but at least the report suite names/variable names are on the wishlist currently. :) For the Launch property name - this is a bit trickier given the API _and_ if a user is self-hosting we cannot get that data. I'll add it to the list, but no promises on that front.

**Comment by Jayap3** [comment]
thanks for the consideration. Just wanna put my thoughts on the debug.

**Comment by MisterPhilip** [comment]
Doing a little housekeeping - closing this to clean up the issues list, but it can be tracked via #46 as it will cover this use case.
