### ISSUE TITLE
APP+WEB event hits not shown in Omnibug

### ISSUE THREAD

**Issue by SL-Gary** [MisterPhilip/omnibug#108]
**Describe the bug**
Omnibug doesn't show 'page_view' event hits for certain domains, yet does for others. In all instances I can see hits leaving the browser when checking in the network tab and looking for 'collect'.

app+web pageview tracking implemented via GTM and data is populating correctly but its not shown in Omnibug.

**To Reproduce**
Example: [https://www.searchlaboratory.com/](url)

**Expected behavior**
I'd expect 'page_view' event output shown in Omnibug

**Example**
Chrome HAR file [https://we.tl/t-dRADvvyUtp](url) shows the event hit in network tab

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10]
 - Browser [e.g. chrome]
 - Version 84.0.4147.105
 - Omnibug Version 1.16.0

Thanks

**Comment by MisterPhilip** [comment]
Sorry it took so long to get fixed; you should start to see v1.16.1 rolling out over the next few days. Let me know if you run into issues :)
