### ISSUE TITLE
Large numbers are being displayed as dates

### ISSUE THREAD

**Issue by annihilate** [MisterPhilip/omnibug#11]
Hi

It seems large numbers that could be timestamps are being displayed as dates when viewed in Omnibug.

If I do:   s.transactionID = '1133944497';

When displayed in Omnibug it is as follows:

Transaction ID  "Wed Dec 07 2005 08:34:57 GMT+0000 (GMT Daylight Time)&nbsp;&nbsp;[1133944497]"

Same issue also occurs for eVars.
i.e. s.eVar7 = '1133944497'; 
Will also display in Omnibug as a date.

Smaller numbers like s.transaction = '1234';  
Will display correctly in Omnibug.

**Comment by simpsora** [comment]
@MisterPhilip What are your thoughts about this one?  So far I've been pretty liberal with converting numbers to timestamps, but it's not always desired.  I can't decide between a white/blacklist, a bounds check, or something else.

**Comment by MisterPhilip** [comment]
@simpsora I honestly can't remember a time that I've passed a timestamp as a value. I really have only had the system-generated ones in my requests. My vote would be for whitelisting the parameter in the providers (either in handleQueryParam or create a new object for timestamps) and possibly provide an option for converting other parameters to a timestamp if it matches the right format. Starting off with whitelisting should be a good start though.

**Comment by MisterPhilip** [comment]
@simpsora - are you OK with changing this to only converting on select parameters?

**Comment by MisterPhilip** [comment]
This should be fixed in the latest version - please let me know if that is not the case!
