### ISSUE TITLE
Can we capture 2 beacon calls in single test

### ISSUE THREAD

**Issue by harichandana107** [MisterPhilip/omnibug#125]
In my case 
We have same key names, same providers , beacon names also same.only event and values will change. Is there any chance that we can cover 2 beacon calls at a time one is for click another one is for page view .

Analytics should trigger 2 times

Tried wait technique but it doesn’t work, 
 We are using frame work chai and puppetry 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser [e.g. chrome]
 - Omnibug Version [e.g. 1.6.0]

**Additional context**

**Comment by MisterPhilip** [comment]
I'm not really sure what you're referring to here. Can you post examples of what you're seeing vs. what you'd expect to see?

**Comment by MisterPhilip** [comment]
Closing this out due to inactivity and lack of information. Feel free to reply with more details if you're still having an issue!
