### ISSUE TITLE
I tried to install and use Omnibug chrome extension but it isn't working.

### ISSUE THREAD

**Issue by Ash1987-Omnibug** [MisterPhilip/omnibug#129]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Omnibug Version [e.g. 1.6.0]

**Additional context**

**Comment by MisterPhilip** [comment]
Can you provide any additional information? I'm not sure how far you've gotten/what you're seeing here.

**Comment by MisterPhilip** [comment]
Closing due to lack of information. Feel free to add more details if you are still having issues!
