### ISSUE TITLE
Bug: Rename parameters stopped working

### ISSUE THREAD

**Issue by dimitriDries** [MisterPhilip/omnibug#130]
Hi, 

Since a couple of months the "rename parameters" function seems to have stopped working. I made no changes to the JSON code and it was working perfectly before. 

Could it be that there is a bug in this function? Or could there be another explanation?

Best regards.

**Comment by MisterPhilip** [comment]
I'm seeing the same thing. Will take a look!

**Comment by dimitriDries** [comment]
Hi @MisterPhilip , Any update on this bug?

**Comment by MisterPhilip** [comment]
Not yet, unfortunately. I started a new job back in mid/late Sept, so I've been busy with that... I'm hoping to look at it this weekend though!

**Comment by dimitriDries** [comment]
Perfect, thanks @MisterPhilip !
