### ISSUE TITLE
Support for the v3 Adobe Media SDK calls

### ISSUE THREAD

**Issue by matt-cheng** [MisterPhilip/omnibug#131]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an enhancement. It would be great to be able to see calls from the Adobe Media Javascript 3.X SDK come through Omnibug rather than having to use the Network tab in the browser dev tools.

**Describe the solution you'd like**
To have the ability to see v3 calls through Omnibug

**Describe alternatives you've considered**
Using the Network tab to view calls

**Additional context**
Adobe Documentation: https://adobe-marketing-cloud.github.io/media-sdks/reference/javascript_3x/index.html

**Comment by MisterPhilip** [comment]
This is currently in the publish process and hopefully should be approved in the next few days.
