### ISSUE TITLE
v3 Adobe Media SDK custom context variables are not parsed out

### ISSUE THREAD

**Issue by matt-cheng** [MisterPhilip/omnibug#134]
**Is your feature request related to a problem? Please describe.**
This is an enhancement. custom context variables are not parsed out when the v3 adobe media sdk is used

**Describe the solution you'd like**
custom context variable to be parsed out in a friendly format. I see it in the request/post data but it's not parsed out.

**Describe alternatives you've considered**
Using the Network tab to view calls

**Additional context**
Related to https://github.com/MisterPhilip/omnibug/issues/131
Adobe Documentation: https://adobe-marketing-cloud.github.io/media-sdks/reference/javascript_3x/index.html

**Comment by MisterPhilip** [comment]
If you're able to send me a URL where you have this deployed to ensure that I have it setup right, that'd be great. If you're uncomfortable posting it publicly, you can email me philip@omnibug.io.

**Comment by MisterPhilip** [comment]
Sorry this took so long! I thought I had released it in Dec, but apparently only added it in the dev branch. Should be rolling out this week!
