### ISSUE TITLE
Ensighten: not matched (self-hosted and/or nexus-test.ensighten.com)

### ISSUE THREAD

**Issue by allankronmark** [MisterPhilip/omnibug#136]
**Describe the bug**
When testing Ensighten (e.g. via Charles Proxy), hostname is rewritten to nexus-test.ensighten.com.

Additionally, the Bootstrap.js can be self-hosted (or otherwise served from the parent domain, e.g. via DNS magic).

**To Reproduce**
1. Go to https://www.dr.dk
2. Open the chrome developer console and Inspect the network.
3. Note Bootstrapper.js request URL.
3. Compare with omnibug.

**Expected behavior**
The pattern for matching the Bootstrapper.js needs to take into account **self-hosted**.
Additionally, a regex pattern might be needed in order to match requests going to either nexus.ensighten.com **OR** nexus-test.ensighten.com.

**Comment by MisterPhilip** [comment]
Self-hosted files have been my nemesis for Omnibug, unfortunately. The problem is if you can rename the file, or the file is generically named (bootstrap.js is pretty generic), we run into false positives rather than false negatives. 

I can definitely update for nexus.ensignten vs nexus-test.ensighten, but let me chew on the self-hosted part a little more.

**Comment by allankronmark** [comment]
To my knowledge they are always identified by the filename Bootstrapper.js - only the publish path is different.

A possible future feature could be to allow users to add their own patterns for matching.

Anyway, I think you’ve created a superb tool -I really appreciate it :)

**Comment by MisterPhilip** [comment]
Sorry this took so long - but it is in the process of being released across all browsers (give it a few days usually). Given that the [Bootstrap framework](https://getbootstrap.com) uses bootstrap.js as their file name (the non-minified version) and the popularity of that framework, I don't think we'll be able to reliably capture self-hosted files unfortunately :(
