### ISSUE TITLE
Glassbox Support

### ISSUE THREAD

**Issue by ironhide1975** [MisterPhilip/omnibug#155]
Can you please include Glassbox support in your tool. Thanks

**Comment by ironhide1975** [comment]
Some additional information, the Glassbox request can be found in the Network panel searching for cls_

**Comment by ironhide1975** [comment]
Hey checking to see if there is any update on adding this to Omnibug. I know your freakishly busy.

**Comment by MisterPhilip** [comment]
Hey @ironhide1975,  sorry this dropped off my radar. Are you wanting to see _every_ request or just that glassbox exists on the page? I'm seeing a server call every ~10 seconds and data in here that could be overwhelming, e.g. the event param value:

`kz1kztfq~19~-~EMThnXzZpc18wX3Qy~selectorActionCount.0_5*eventId.0_d~-~-~-~~kz1kztfq~106~-*0(0)*0*0*0*SECTION(8)*0(1)*UL~NeyJ0eXBlIjoiaG9yaXpvbnRhbFNjcm9sbGJhciJ9~selectorActionCount.0_1*eventId.0_e~-~-~body%20%3E%20div%20%3E%20div%20%3E%20div%20%3E%20div%20%3E%20section.fullWidthSlider.swipe-slider.p-tb-100.background-lightGrey%20%3E%20div.scroll-snap-wrapper%20%3E%20ul~~kz1kzw6q~27~-~-~co.3_aHJfMXYy*selectorActionCount.0_6*eventId.0_f~-~-~-~~kz1kzw6r~29~-~Nhr_1v2*iu_1v7*jm_1vb*kq_1vh*li_1vl*m4_1vp*mz_1vu*nl_1vy*oe_1w3*p0_1w7*pr_1wc*qk_1wh*r6_1wm*rw_1wr*sq_1ww*tf_1x1*u3_1x6*uu_1xd*vj_1xj*w6_1xo*ww_1xu*xl_1y1*y8_1y6*yt_1yc*yv_px*zb_qu*z6_rf*z4_s0*z0_sl~ft.0_8j*selectorActionCount.0_7*eventId.0_4r~-~-~-~~kz1kzxof~29~-~Ny1_21h*yc_20v*ym_20a*yv_rg*z7_qu*zb_oz~ft.0_9h*selectorActionCount.0_8*eventId.0_6h~-~-~-`

**Comment by ironhide1975** [comment]
Good question, I'm guessing every hit, even though yes that would be overwhelming.Although at the end of the day most of the times we just want to make sure the tool is working on the page. I defer to whatever is easier to code.
