### ISSUE TITLE
Adobe AEP Web SDK ?

### ISSUE THREAD

**Issue by ckdigital21** [MisterPhilip/omnibug#159]
**What is the name of the provider (marketing tool) you are wanting to add?**
Just curious if you plan to add some of the newer analytics tools emerging:
Adobe Experience Platform Web SDK (alloy.js implementation)
and/or Google Analytics 4
and/or Amplitude

**Please provide any links to their product pages, documentation, etc.**
[Ideally add links to their product homepage, technical documentation, etc.]
https://experienceleague.adobe.com/docs/experience-platform/edge/home.html?lang=en
https://experienceleague.adobe.com/docs/experience-platform/edge/fundamentals/debugging.html?lang=en
https://webanalyticsfordevelopers.com/2021/01/19/adobe-experience-platform-web-sdk/
https://www.qa2l.com/blog/200-debugging-alloy-js-implementations

**Do you have a sample page this is currently on?**
I've been watching a potential employer add AEP Web SDK to miamiherald.com - I see it in Observepoint and the Adobe debug tool above, but I have found Omnibug to be a better all around tool. 
On the other hand, AEP is new to me, and I don't know if it lends itself to easy inclusion to a tool like Omnibug (i.e., don't know how much custom code occurs - for instance, I can see where miamiherald.com is passing evar values in "post body", but I thought one use of AEP might be to send context data instead of specifying evar or prop.... not sure, will have to read up on that....

**Additional context**
Add any other context about the provider / tool here.

**Comment by MisterPhilip** [comment]
Hi there! 

GA4 is already included, so you should be seeing that already. If you're not, please let me know and I can take a deeper look.

AEP SDK is on my list to eventually add. I haven't had a ton of time to give some much needed love to Omnibug, but I hope to in the coming weeks. AEP SDK should be easy enough for me to add though!

And Amplitude I honestly don't have any experience with, so I'd need to research what their implementation is like to see how possible it would be to add.

**Comment by ckdigital21** [comment]
Thanks!

Yes, I see GA4 now.... looks like they always use an account ID starting
with "G-"  instead of UA-
https://www.monsterinsights.com/docs/google-analytics-4-versus-universal-analytics/

Let me just say that your feature of being able to highlight different
tracking elements is incredibly useful, and one of the things that sets
Omnibug apart - makes it easy to see what's important quickly, whether I'm
working with my own debugging or just trying to learn by looking at others.

**Comment by jeysaravana** [comment]
@MisterPhilip thank you for the awesome addons
do you have any rough estimate on when Adobe AEP Web SDK will be available?

**Comment by MisterPhilip** [comment]
Initial version released in 3269371667dbeb8271c1a79c1a4b5a38cd756b60 (v1.20.0)
