### ISSUE TITLE
FullStory

### ISSUE THREAD

**Issue by irv-fs** [MisterPhilip/omnibug#183]
**What is the name of the provider (marketing tool) you are wanting to add?**
FullStory

**Please provide any links to their product pages, documentation, etc.**
Ideally add links to their product homepage, technical documentation, etc.
https://fullstory.com
https://help.fullstory.com
https://developer.fullstory.com

**Do you have a sample page this is currently on?**
It is used by many fortune 500 customers, but you can see it in action at this site: https://fruitshoppe.firebaseapp.com/#/

**Additional context**
I work for this company and am researching for a major retailer who wants to see FullStory in OmniBug.  I am willing to help code this if necessary.

**Comment by MisterPhilip** [comment]
Added in 75582b4, will be available in v1.22.0. Sorry for the delay!
