### ISSUE TITLE
Omnibug does not display MacOS Edge

### ISSUE THREAD

**Issue by thewoody** [MisterPhilip/omnibug#184]
**Describe the bug**
I can't see an Omnibug tab in developer tools.

**To Reproduce**
1. Go to Edge on MacOS (10.15.7)
2. Installed addon from Edge Store and enabled "Private"
3. Opened developer tools
4. Unable to see Omnibug tab
5. Used the double chevron to expand and not there
6. Clicked on the "+" to the right of the double chevron and I can't see Omnibug there either
7. Restarted the browser and followed steps 3 and still not showing

**Expected behavior**
Expecting to see an Omnibug tab

**Screenshots**
I think the description is clear enough, but happy to provide if needbe

**Desktop (please complete the following information):**
 - MacOS 10.15.7
 - Edge 99.0.1150.52 (Official build) (x86_64)
 - Omnibug Version 1.19.0

**Comment by MisterPhilip** [comment]
When you open the window - is it a normal window or a private window? If you open it on a new tab without loading a website, does it not show? If it is only when loading a website, is likely related to #181.

Also, the usual suggestion of reinstalling it might help but let me know if not! :)

**Comment by thewoody** [comment]
It was normal and private.  I've uninstalled the plugin and re-installed it and it now works. THANK YOU! :-)
