### ISSUE TITLE
I can see all the calls are doubled on Omnibug

### ISSUE THREAD

**Issue by darpan9935** [MisterPhilip/omnibug#186]
I can see all the calls to Adobe and other pixels are dooubled from today while I can see single call on network tab.

![image](https://user-images.githubusercontent.com/24822913/161597540-3bd37df2-f329-4d3e-be70-ddb7007000ae.png)

Thanks,
Darpan

**Comment by MisterPhilip** [comment]
Noticed this today too, taking a look.

**Comment by MisterPhilip** [comment]
Doing a little housekeeping - closing this to clean up the issues list,; I believe this was already fixed but let me know if you see it again.
