### ISSUE TITLE
Omnibug is not shown in developer tools

### ISSUE THREAD

**Issue by EOSRG** [MisterPhilip/omnibug#193]
**Describe the bug**
Omnibug is not shown in developer tools

**To Reproduce**
1. using chrome Version 101.0.4951.64 
2. https://www.rebelsport.com.au/mens/shoes
3. open developer tools
4. omnibug is not shown

**Expected behavior**
omnibug is shown

**Screenshots**
![image](https://user-images.githubusercontent.com/103472490/167784533-b3b1efe2-aaa0-4613-a2d0-36218b7edabe.png)
![image](https://user-images.githubusercontent.com/103472490/167784565-76080f89-c70f-429d-b018-2b28cf7f6a97.png)
![image](https://user-images.githubusercontent.com/103472490/167784702-71849a81-9704-48cb-9e5b-64076344a642.png)

**Comment by MisterPhilip** [comment]
Please see #181 for more information
