### ISSUE TITLE
User_ID is not showing in Omnibug for GA4

### ISSUE THREAD

**Issue by ironhide1975** [MisterPhilip/omnibug#212]
Loading a page with GA4, viewing the output for GA4, I do not see a user_id variable even is one is sent and verified in Google Tag Manager.

**Comment by MisterPhilip** [comment]
Cannot reproduce this for GA4 across multiple sites, e.g.:
![image](https://user-images.githubusercontent.com/950141/221381135-54431f13-ff5a-498c-b86f-ac6e1e4f65b0.png)

When you say it is verified in GTM, are you seeing the value there mapped to the tool, or just that the variable has a value?

**Comment by ironhide1975** [comment]
Disregard this bug. I didn't see that the UserID is being sent at the top of the Page View data in General, compared to Other section at the bottom where our UserID2 was being sent.
