### ISSUE TITLE
Google Analytics 4 tags not showing

### ISSUE THREAD

**Issue by hannahls1** [MisterPhilip/omnibug#216]
Hi,

Was wondering if you could help me. I believe I am unable to see GA4 notifications in my omnibug view - do you know if there is an issue whereby GA4 tags aren't visible? As well as the site I am working on, I have checked with the Google merch store (which has GA4 tagging in place) and I can't see the GA4 tags coming through here either. 

Do you know I view this?

Thanks,
Hannah

**Comment by MisterPhilip** [comment]
Hi @hannahls1 - so sorry for the delay, it's been a year! Are you still experiencing this issue? I just pushed a change out (v1.21.0) that splits GA4 and UA so it may fix any issue you have. Let me know if you are still seeing it.
