### ISSUE TITLE
RudderStack

### ISSUE THREAD

**Issue by ryanmccrary** [MisterPhilip/omnibug#223]
**What is the name of the provider (marketing tool) you are wanting to add?**
RudderStack

**Please provide any links to their product pages, documentation, etc.**
https://rudderstack.com
https://www.rudderstack.com/docs/

**Do you have a sample page this is currently on?**
https://rudderstack.com
https://

**Additional context**
The API/SDK is fully compatible with segment, so /page /track and /identify events and endpoints would be treated as same.

**Comment by MisterPhilip** [comment]
Looks easy enough! I will work on getting this added later this week.
