### ISSUE TITLE
GA4 - Batched Events Missing / Not Separated w/Debugger Off

### ISSUE THREAD

**Issue by flist87** [MisterPhilip/omnibug#241]
**Describe the bug**
When GA4 is not in debug mode, it starts **batching events together**, for those that are within **close timing proximity**.

This makes sense from a site performance perspective, lower connections/requests of the browser, however, Omnibug isn't expecting batched GA4 events. It only sees the first hit and name of that hit, i.e. page_view. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'hellyhansen.com/en_us/'
2. Click on dev/inspection drawer, 
3. Scroll down to see GA4 hits, filtered with 'G-' and ensure GA4 is ticked on
4. See first hit, page_view, with (hopefully) no other events logged in Omnibug.
5. Now actually inspect the measurement protocol hit, it has multiple events, i.e. vie_promotion (hopefully)

**Expected behaviour**
I expect Omnibug to know we are NOT in debug mode and for it to know there's a chance GA4 might also append other event data/info. It needs to break down the hit string/params to see there's multiple (I think en=?) event names being sent?

**Screenshots**
![Screenshot 2023-10-20 at 11 06 01](https://github.com/MisterPhilip/omnibug/assets/19697870/414cb351-d614-41b4-95ee-547a945122e9)
<img width="1010" alt="Screenshot 2023-10-20 at 11 11 55" src="https://github.com/MisterPhilip/omnibug/assets/19697870/f576c3af-cd04-4bf7-bf88-a085830956d9">
![Screenshot 2023-10-20 at 11 14 28](https://github.com/MisterPhilip/omnibug/assets/19697870/0e5ec837-c7df-4df3-a936-a7f939d1ad16)

**Desktop (please complete the following information):**
 - OS: [iOS 13.2.1 (22D68)]
 - Browser [Chrome: Version 118.0.5993.70 (Official Build) (arm64)]
 - Version [e.g. 118]
 - Omnibug Version [e.g. v1.22.0]

**Additional context**

**Comment by MisterPhilip** [comment]
Yeah, this is on the list for v2 (see #233). Omnibug does parse out multiple events in the full window, just not in the individual row.
![image](https://github.com/MisterPhilip/omnibug/assets/950141/b6582335-bb5b-4fa1-9a6d-f57cdc0c9365)


I've played around with adding the event count in the pill but it got in the way more than it helped. I do like ercanyuz's idea with hovering so you can quickly see them. I can probably have that added before v2.
