### ISSUE TITLE
New Tag - Vibes Tag

### ISSUE THREAD

**Issue by ironhide1975** [MisterPhilip/omnibug#243]
Request to add the Vibes tag to detection. 
https://www.vibes.com/

Standard setup has base tag, add to cart, remove from cart, begin checkout and purchase.

**Comment by MisterPhilip** [comment]
I'm struggling to find relevant docs or examples, do you have any?

**Comment by ironhide1975** [comment]
Try this...
https://developer-platform.vibes.com/docs/add-tag-tracking-to-your-campaign
