### ISSUE TITLE
Highlight Parameters

### ISSUE THREAD

**Issue by Sbermolone** [MisterPhilip/omnibug#244]
Would it be possible to get a list of available parameters that can be added to Omnitag?

**Comment by Sbermolone** [comment]
Sorry,

I guess I was kind of vague. Basically, I see that you can change and add parameters to Omnibug but I am fairly new to the tool and I don’t know what parameters are available to include. I was just wondering if there was a list out there that I could peruse?

Sincerely,
Sam Bermolone


Sam Bermolone
Associate Director, Ad Operations
212-915-2188

**Comment by MisterPhilip** [comment]
Ah, I gotcha! Unfortunately, I don't have a full list of the parameters that are captured today. The closest would be to look through the code and see what is / is not available. 
https://github.com/MisterPhilip/omnibug/tree/master/src/providers

I do have a full list of providers (tools) that Omnibug supports here:
https://omnibug.io/help/supported-tags/

**Comment by MisterPhilip** [comment]
Closing as stale/no response.
