### ISSUE TITLE
Dynamic Yield- AB Testing Platform

### ISSUE THREAD

**Issue by azizo888** [MisterPhilip/omnibug#250]
**What is the name of the provider (marketing tool) you are wanting to add?**
Dynamic Yield 

**Please provide any links to their product pages, documentation, etc.**
(https://www.dynamicyield.com/)

**Do you have a sample page this is currently on?**
It is on flooranddecor.com

**Additional context**
Add any other context about the provider / tool here.

**Comment by azizo888** [comment]
I don't see DY added in omnibug. Was it added?

**Comment by MisterPhilip** [comment]
I _just_ added it and it is currently publishing to the various extension stores. Firefox is live now, Chrome is usually a few days, and Edge is usually a week.
