### ISSUE TITLE
GTM not appearing when enabled in filters

### ISSUE THREAD

**Issue by jpool-cf** [MisterPhilip/omnibug#260]
GTM does not appear in the list of tags/providers when enabled in the filters.

Seems to be an issue upon initial load/reload of a site. Navigating away to another site and returning then produces the expected behavior of GTM appearing, but not on subsequent page loads.

Repro
- Open Omnibug and ensure GTM is enabled in filters
- Open site known to have GTM deployed
- GTM does not appear in the list of results
- Navigate away from site to google.com
- Browser back button to previous site
- GTM now appears in list of results as expected
- Additional page loads on same site do not show GTM

Edge v126.0.2592.87 or Chrome v126.0.6478.127
Omnibug v1.24.0

**Comment by MisterPhilip** [comment]
Thanks for the report, I can't say I've seen this happen before. To confirm, in your first session before you navigate to Google.com, every page view that happens does not show GTM? It's only when you return to the site?

**Comment by jpool-cf** [comment]
> To confirm, in your first session before you navigate to Google.com, every page view that happens does not show GTM? It's only when you return to the site?

Correct. Though now I can't repro of course... :D

**Comment by MisterPhilip** [comment]
Of course, haha! I'll close this but feel free to ping me if you're able to replicate.
