### ISSUE TITLE
User Parameters not showing on subsequent hits. 

### ISSUE THREAD

**Issue by ironhide1975** [MisterPhilip/omnibug#261]
**Describe the bug**
In GA4, on subsequent hits I am not seeing user parameters in Omnibug, even though they are showing in GTM debugger. Note: The site I'm using is a single page app.

**To Reproduce**
1. Go to a site with user parameters.
2. Load the page and pass user parameters in the page_load event.
3. Validate parameters in Omnibug, validate GTM
4. Click to go elsewhere on the site (it actually loads other content)
5. Validate Omnibug, validate GTM

**Expected behavior**
User parameters should be available in all hits.

**Screenshots**
Unable to due to internal application. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : Version 126.0.6478.127 (Official Build) (64-bit)
 - Omnibug Version [e.g. 1.6.0]: 1.24.0

**Additional context**
Thanks Phil!

**Comment by MisterPhilip** [comment]
It looks like this is expected; I didn't see it in the raw network request, and their docs suggest this is expected! I'm guessing the GTM debugger shows the persisted value.

https://support.google.com/analytics/answer/12370404?sjid=11611976904282335096-NC#zippy=%2Cgoogle-tag-websites:~:text=User%20property%20deduplication
> Google Analytics collects a user property from your website when the user property is set for the first time on a page (usually through the first events on a page) or when the value assigned to a user property changes.
> 
> When a user performs an action that changes the value of a user property, Analytics will collect only the value that changed. For example, your entire checkout flow is on one page. Someone makes a large purchase on your site so the value assigned to your purchaser_size user property changes at the end of the checkout flow; however, their age and location haven't changed. Analytics will only collect the purchaser_size user property when the value changes.
