### ISSUE TITLE
Chrome "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions."

### ISSUE THREAD

**Issue by svetlev** [MisterPhilip/omnibug#262]
In the Chrome Web Store, it says for OmniBug that "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions." Can you follow best practices? We can't loose this tool! Thanks!

**Comment by MisterPhilip** [comment]
Yeah, it's on the list to fix up soon. Most of the work has already been done, but there have been numerous challenges & bugs with the migration to manifest v3. Many of which Chrome did not consider a use case like ours for unfortunately.

**Comment by jhornych** [comment]
Which branch contains the v3 version?

**Comment by MisterPhilip** [comment]
> Which branch contains the v3 version?

It's currently all local, in final testing

**Comment by MisterPhilip** [comment]
I will be doing a slow roll out for this to ensure no major issues, but Omnibug v2.x includes Manifest v3 which will get us back to Chrome's "best practices".

**Comment by MisterPhilip** [comment]
100% rolled out, everyone in Chrome should have 2.0.1 now.
