### ISSUE TITLE
Grouping Events Together Unwillingly

### ISSUE THREAD

**Issue by shelbykolb** [MisterPhilip/omnibug#266]
Hello,

All of a sudden today, Omnibug started bundling my events and it makes the interface extremely frustrating for me. This is very poor timing as we had a huge site launch last night that I am needing to track and QA. 

![image](https://github.com/user-attachments/assets/0c54fda9-8d5d-468d-a353-be22fd0511a4)

![image](https://github.com/user-attachments/assets/ccf9cdcb-1d32-46db-9453-e156dc5ea49c)

They should be showing as different events as they were always doing before. My teammates using Omnibug report that this has always happened on their end, but it never did for me. Please help me revert this back ASAP.

Thank you!

**Comment by MisterPhilip** [comment]
Hi! 

Multiple events in a single call has always been the case for GA4, Omnibug has just done a poor job showing it in the interface. In the latest update, you'll now see the number of events and all the event names within the request. However, the underlying issue of multiple events showing up in one request has always been there (source: [Google's documentation, see "Understand event grouping"](https://support.google.com/analytics/answer/9322688?hl=en&ref_topic=9756175#zippy=%2Crealtime-report%2Cdebugview-report:~:text=Understand%20event%20grouping)).

I'm closing this as we have another issue already open to better display the batched hits (#233), but please keep in mind that this is a high priority item for me in the next major version of Omnibug (in development).
