### ISSUE TITLE
DEFECT - Filter Requests/Enabled Providers Malfunctioning

### ISSUE THREAD

**Issue by okn0003** [MisterPhilip/omnibug#267]
**Describe the bug**
The **Filter Requests** setting is not executing the selected option of choice. I keep getting unwanted requests popping up. 
For example, I selected only Adobe Analytics, but a bunch of other random requests is coming thru.

The **Enabled Providers** setting does not work either. Same results as the feature above, still getting unwanted requests popping up.
For example, I selected only Adobe Analytics, but a bunch of other random requests is coming thru.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome 
 - Browser Version: 127.0.6533.100
 - Omnibug Version: 2.0.1

**Screenshots**
Request Arrived
![Requests Arrived](https://github.com/user-attachments/assets/745833b6-4d82-4602-a8e5-507e62b947dc)
Filter Requests Setting
![Filter Requests - Selection Option](https://github.com/user-attachments/assets/8a0862e5-7f52-40ea-97e7-4c947f3221c4)
Enabled Providers Setting
![Enable Providers - Selection Option](https://github.com/user-attachments/assets/f751f698-a6ac-41b3-98b0-4d82f421bfb2)

**Comment by MisterPhilip** [comment]
Enabled providers is a known issue for me with the recent release, however the filtering should still work. Let me dig into it and see if the enabled providers bug is causing more havoc here. Thanks for the report!

**Comment by hellojsl2024** [comment]
I am experiencing the same issue regarding the filter requests.

**Comment by MisterPhilip** [comment]
@okn0003 / @hellojsl2024 - this is fixed in 2.0.2 which was approved this morning in Chrome & Firefox. Edge will take longer but if you use either of those browsers you should be set. Let me know if you run into any issues with it.

**Comment by hellojsl2024** [comment]
@MisterPhilip it's working perfectly now, thank you!
