### ISSUE TITLE
Could not load background script 'libomnibug.js'.

### ISSUE THREAD

**Issue by shivani147** [MisterPhilip/omnibug#39]
Hi, 
I have taken a checkout of the project and I am trying to load this extension from my local machine, pointing to chrome directory in "load packed extension", so  it is giving me the following error  
"Could not load background script 'libomnibug.js'".

**Comment by shivani147** [comment]
![screenshot from 2017-02-13 14-28-36](https://cloud.githubusercontent.com/assets/8521972/22876928/f4faeba6-f1f8-11e6-9582-515f37cffca9.png)

**Comment by simpsora** [comment]
Hi @shivani147, `libomnibug.js` is a generated file.  Before loading the extension locally, you'll need to run the `concat` grunt task:

```
[00:08:36] rosssimpson@fhqwhgads ~/code/omnibug (master $%=) $ grunt concat
Running "concat:chrome" (concat) task
File "chrome/libomnibug.js" created.

Running "concat:firefox" (concat) task
File "firefox/chrome/content/omnibug/libomnibug.js" created.

Done, without errors.
```

That will generate the file, and you'll be able to use the extension locally afterwards.
