### ISSUE TITLE
Omnibug is not loading

### ISSUE THREAD

**Issue by Haridharani95** [MisterPhilip/omnibug#44]
I added omnibug extension to the chrome but its not loading anything.Do we need to add anything extra
![omnibug error](https://user-images.githubusercontent.com/29428700/27129907-a40b122e-5121-11e7-8c7d-44a1f696b5fc.PNG)
Kindly resolve as soon

**Comment by MisterPhilip** [comment]
You'll need to go to a page that has one of the supported tools for it to show any content. Google's homepage usually doesn't have many external tracking tools installed on it.

**Comment by MisterPhilip** [comment]
Closing due to age, but let me know if you still have issues.
