### ISSUE TITLE
Add new providers

### ISSUE THREAD

**Issue by MisterPhilip** [MisterPhilip/omnibug#53]
New providers, as suggested by the community:

- [x] [Adobe Heartbeat](https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/)
- [ ] [Nelsen DCR](http://en-us.nielsen.com/sitelets/cls/dcr.html)
- [ ] [Webtrekk](https://www.webtrekk.com/en/home/)
- [ ] [comScore](https://www.comscore.com/)
- [ ] [Decibel Insight](https://www.decibelinsight.com/)
- [x] [Segment](https://segment.com/)
- [x] [Matamo](https://developer.matomo.org/api-reference/tracking-api)

**Comment by kenhowardpdx** [comment]
Would you consider adding [Segment](https://segment.com)?

**Comment by shoestar** [comment]
Hi, not sure if this is the right place to request a new provider but [Lytics](https://www.lytics.com/) (a customer data platform like Segment) would be very helpful.

**Comment by johndavidsimmons** [comment]
@shoestar Looks like the parameters collected are outlined [here](https://learn.lytics.com/documentation/product/features/lytics-javascript-tag/using-version-3/installation-configuration) and [here](https://learn.lytics.com/documentation/product/features/lytics-javascript-tag/using-version-3/collecting-data#what-data-is-collected?). 
Do you know of a site (or two) that are using Lytics?

**Comment by shoestar** [comment]
Nice finding @johndavidsimmons! I know that lytics.com itself is using it. I also looked at their [customer references](https://www.lytics.com/customer-stories) but I couldn't find the requests on their websites. But using a [source code search engine](https://publicwww.com/websites/c.lytics.io/) I found additional sites like www.akamai.com.

**Comment by johndavidsimmons** [comment]
@shoestar @MisterPhilip 
I have added the lytics provider in a branch called lytics

**Comment by MisterPhilip** [comment]
Thanks @johndavidsimmons  - I'll review in the next day or two and get a new build out once approved!

**Comment by shoestar** [comment]
Excellent! Thanks to you both! How can I buy you a beer?

**Comment by jaredrileysmith** [comment]
@johndavidsimmons I got the TikTok events to work locally (still some forgetting to work on), but am having trouble getting the icon to display.  I read your Medium article on the subject & added the icon in the 16x16 png format to the icons file and updated the scss accordingly, but I must've missed something.  Any guidance would be greatly appreciated.![image](https://user-images.githubusercontent.com/26010307/91002640-d33afb80-e594-11ea-8009-9c2c49512e69.jpeg)

**Comment by johndavidsimmons** [comment]
🤔 🤔 🤔  Does the _key field match the file name? The filename should be _key16x16.png and be in the same folder with all the other icons, and be declared in the incons.scss file like below
<img width="770" alt="Screen Shot 2020-08-24 at 8 49 19 AM" src="https://user-images.githubusercontent.com/8012764/91046769-0312ef00-e5e7-11ea-92aa-ac776a6589be.png">

**Comment by jaredrileysmith** [comment]
@johndavidsimmons AFAIK all the requirements you provided are being met.  I will keep looking into my implementation, but any other help you can provide is greatly appreciated as well.
![image](https://user-images.githubusercontent.com/26010307/91069286-d4067880-e5fa-11ea-87cf-14a3bc0e1b3b.png)

**Comment by MisterPhilip** [comment]
It matches off of the provider name, not the key. I'd recommend changing the provider name to just "TikTok" anyways, unless "Events" is the product name.

**Comment by jaredrileysmith** [comment]
@MisterPhilip makes sense, thanks for the input!

**Comment by johndavidsimmons** [comment]
Oh yeah thats right, sorry @jaredrileysmith, I do this just infrequently enough that I forget it all in between

**Comment by jaredrileysmith** [comment]
@johndavidsimmons  no worries, I definitely appreciate the help.

**Comment by MisterPhilip** [comment]
Closing this out - for any new provider requests, please open a new issue so we can properly track them 😄
