### ISSUE TITLE
Entries do no expand

### ISSUE THREAD

**Issue by soumiazehri** [MisterPhilip/omnibug#57]
Hello.

I have been using Omnibug on many months on Chrome, but all of a sudden, I do not seem to be able to extend the entries like I use to. Is there a quick fix. I have restored original settings on Chrome, but it still did not change anything. Best

**Comment by MisterPhilip** [comment]
What version of Chrome are you using (Help > About), and what version of Omnibug is installed (More Tools > Extensions)?

**Comment by MisterPhilip** [comment]
This should be fixed in the latest version - please let me know if that is not the case!
