### ISSUE TITLE
Omnibug Log Files Disapeared 

### ISSUE THREAD

**Issue by jansara66** [MisterPhilip/omnibug#58]
Hi Philip

Thanks so much for making Omnibug. I appreciate all the efforts to keep it current. The latest adaptation for Firefox seems to have dropped the "Log File" feature. The only reason I used Omnibug in Firefox (Firebug) over Chrome was to capture events in a log file that could then be reviewed post testing. This was far more efficient than reading the individual events as they occur when debugging large processes (many pages and events). Please advise if this is now lost as Omnibug had to be moved from Firebug to Developer Tools, or if there are other ways to log Omnibug tests.

Thanks again,
-Jane

**Comment by MisterPhilip** [comment]
It's coming back soon, promise! When we migrated to the new style of add-ons for Firefox, we didn't have the same APIs on the backend to export logs. However, I've been working on a revamp of the entire plugin, and being able to export the requests is definitely coming back! I plan on doing an open beta for the new version within the next couple of weeks, with a full release sometime in March.

**Comment by jansara66** [comment]
That sounds fantastic! thanks so much for the quick reply.

**Comment by jansara66** [comment]
Hi Philip

Thanks so much for the latest updated to Omnibug. It's great to work with log files again. I updated my Omnibug template (an Excel file) to match the new data structure. [Omnibug-Template.xlsx](https://github.com/jansara66/Omnibug-Template)

**Comment by MisterPhilip** [comment]
Hey, that's awesome! I'll have to pass it around :)

Glad it's working for you again
