### ISSUE TITLE
Chrome extension shows OMINbug logo instead of omnibug

### ISSUE THREAD

**Issue by steffencrespo** [MisterPhilip/omnibug#73]
### Browser & Omnibug versions
Current; chrome

### Expected behavior
Picture with Omnibug logo and not OMINBUG

### Actual behavior
Shows a logo with the word OMINBUG (looks like a typo and made me doubt that I was getting the right extension)

### Steps to reproduce the behavior

1. go to [chrome web store and search for omnibug](https://chrome.google.com/webstore/search/omnibug)
2. look at the list of options - the first is Omnibug but the logo looks wrong 

### Other notes
![image](https://user-images.githubusercontent.com/1045193/54565968-d6d45700-498c-11e9-8437-2dcce19a2672.png)

**Comment by MisterPhilip** [comment]
D'oh! 🤦‍♂️ I'll get this fixed, thanks!

**Comment by MisterPhilip** [comment]
Looks like Google propagated the changes, thanks for the heads up @steffencrespo!

**Comment by steffencrespo** [comment]
That was really quick! Cheers!
