### ISSUE TITLE
How often are updates released?

### ISSUE THREAD

**Issue by DavidLozzi** [MisterPhilip/omnibug#82]
Hi @MisterPhilip, how often are updates released to Chrome store? My team is chompin at the bit for these changes ;)

**Comment by MisterPhilip** [comment]
I usually try to do within a week of a new feature being added. I need to clean up a few things first, but hopefully can get it out by tomorrow night.

**Comment by MisterPhilip** [comment]
95ad569 is now published to the Chrome/Firefox stores. Usually takes an hour to propagate out.
