### ISSUE TITLE
Webtrends Analytics

### ISSUE THREAD

**Issue by nickhillman47** [MisterPhilip/omnibug#86]
This used to work with omnibug but doesn't seem to anymore and is no longer listed in your provider list. Could it be readded?

**Comment by MisterPhilip** [comment]
Hello -

What version of Webtrends are you using? I haven't used WT in years, so it might take a bit for me to re-add it back in.

**Comment by nickhillman47** [comment]
Thanks for your quick response. It’s analytics 9 and 10

 

Nick Hillman | LRPS

Photographer | Web developer |Bread Maker | Cyclist | Walker |Craftsman

Nick@indigomonkey.co.uk

www.indigomonkey.co.uk

**Comment by MisterPhilip** [comment]
Hi @nickhillman47 - 

You should see this within the next few hours in your Omnibug install. Enjoy! :)
