### ISSUE TITLE
Wider or adaptive column width for parameter names

### ISSUE THREAD

**Issue by gh-nobi** [MisterPhilip/omnibug#97]
**Is your feature request related to a problem? Please describe.**
In some cases, the parameter names are too long and get cut-off. It happens mainly with Adobe Target, with names that all start with the same prefix: notifications[0].parameters.PARAM_NAME. In that case, only the start of the parameter name is visible and you have to hover to see it completely.
This is for Chrome.

**Describe the solution you'd like**
3 solutions are possible I guess:
- A wider column to display the param names
- Implement a way to set/change the column width
- Make the column width adaptive: gets wider when the dev panel gets wider

**Additional context**
![image](https://user-images.githubusercontent.com/22093428/74540710-8ec50800-4f40-11ea-8e14-fb4ef0381521.png)

**Comment by MisterPhilip** [comment]
Yeah, this has been a pain point for a while now. I'll tinker with it some to see what works best :+1:

**Comment by MisterPhilip** [comment]
@gh-nobi  - I've added an enhancement that should fix this for you. It's within Omnibug v1.14.0, which is rolling out to browsers right now. It can take a few hours for browsers to update extensions, but once it's updated let me know if you have any other feedback / thoughts!
