### ISSUE TITLE
mParticle not working with v2 SDK

### ISSUE THREAD

**Issue by ScaleToInfinity** [MisterPhilip/omnibug#98]
**Describe the bug**
mParticle releases a v2 of their web SDK, the pattern does not match this, might also need to be checked if something else checked. 

**To Reproduce**
1. Go to https://www.trendhim.com/
2. Check your omnibug
3. Notice that events is not being captured

**Expected behavior**
Events sent to mParticle should be listed.

**Screenshots**

**Desktop (please complete the following information):**
All

**Additional context**
Regex that is no longer valid: https://github.com/MisterPhilip/omnibug/blob/master/src/providers/Mparticle.js#L13

Example event URL: https://jssdks.mparticle.com/v2/JS/us1-57efcd9228826649aacb395919cc5163/Events

Working regex:  /\.mparticle\.com\/v\d\/JS\/.{3}-\w{32}\/Events$/

**Comment by MisterPhilip** [comment]
Thanks for the detailed bug report! I can reproduce the issue and will work on updating mParticle for ya.

**Comment by ScaleToInfinity** [comment]
Sounds awesome Philip!

We plan on using this tool internally for quickly checking what events were fired off to mParticle and then forwarded to Amplitude :D That way it's very clear what data they should look at in Amplitude for specific behavior. 

Thanks for Omnibug! :+1:

**Comment by MisterPhilip** [comment]
This has been published in v1.15.0, but it might take a few days (or even weeks) due to COVID-19 impacting the response time from the various browser extension review teams. Hopefully it'll be up quick for you though. Let me know if you run into any other issues!
